### ISSUE TITLE
add temporal support

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/WFS_FES#57]
Woudc be valuable to add:

- [ ] temporal extent definition in feature collection metadata
- [ ] temporal dimension definition in feature collection to provide clients capability to temporally query features.  (OpenAPI may allow for this already by design by specifying data type along with attribute query property)

**Comment by cholmes** [comment]
+1 - I'd love to see time be more of a first class citizen. I like putting most things in 'extensions', but I think it'd be better with time that the 'extension' is more to opt-out of time. Most features should at least have a published or updated time. 

An awareness of time is a major advantage of WFS over just publishing a file to be downloaded. Should be easy to query just the latest updated features.

**Comment by cportele** [comment]
Having a capability to add the temporal extent, too, makes sense to me.

Could you provide more detail how "temporal dimension definition" is defined and how it should be provided, @tomkralidis ?

**Comment by tomkralidis** [comment]
@cportele definition would follow [CAT 3.0 Record](http://schemas.opengis.net/cat/csw/3.0/record.xsd) `csw30:TemporalExtent`, i.e.:

>
             A type for specifying the temporal extent of the data
             item that a metadata record describes.  Omitting
             begin/end implies infinity in that direction.  The
             attribute "inclusive" can be used indicate whether
             the boundary value in included in extent or not.

so in feature collection metadata, something like:

```json
"temporal_extent": {
    "begin": "2011-11-11T12:22:11Z",
    "end": "2012-11-24T12:32:43Z"
}
```

For temporal dimension definition for query, looking deeper this is simply an OpenAPI type definition to define as RFC3339/ISO8601.

**Comment by rouault** [comment]
For the record, the STAC API (https://github.com/radiantearth/stac-spec/blob/dev/api-spec/spec.yaml) has a `time` parameter:
```
  time:
    name: time
    type: array
    description: An array of date-time strings that adheres to RFC3339 (for example 1985-04-12T23:20:50.52Z). One date-time in the array is the time to match. Two date-times represent a range. Any additional items in the array will be ignored.
    items:
      type: string
in: query
```
